### ISSUE TITLE
`os.mkdir`/`os.makedirs`/`os.mkfifo`/`os.mknod` calls with insecure permissions

### ISSUE THREAD

**Issue by Takishima** [Takishima/pylint-secure-coding-standard#15]

**Comment by Takishima** [comment]
@HorlogeSkynet Do we want to make the plugin warn by default if the permission is not `0 < mode <= 0o755` ?
Or more like in the builtin `open()` vs. `os.open()`, only if the user explicitly specifies a value for the related configuration option?

**Comment by HorlogeSkynet** [comment]
> [...] more like in the builtin `open()` vs. `os.open()`, only if the user explicitly specifies a value for the related configuration option?

I guess more like this, as these methods rely on `umask` too, and thus we may encounter the same static analysis limitations as with `os.open`. So 👍 for #17 if I am not wrong !
